"use client"
import { useState, useEffect } from 'react'
import { collection, query, where, getDocs, deleteDoc, doc, updateDoc } from 'firebase/firestore'
import { db } from '@/config/firebase'
import { useAuth } from '@/context/AuthContext'
import { TrashIcon, PencilIcon, ArrowPathIcon, ChartBarIcon, UsersIcon, CogIcon, CreditCardIcon, ArrowDownTrayIcon } from '@heroicons/react/24/outline'
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

interface User {
  uid: string
  email: string
  isAdmin: boolean
  createdAt: { seconds: number }
  lastLogin: { seconds: number }
}

export default function AdminPanel() {
  const { user } = useAuth()
  const [users, setUsers] = useState<User[]>([])
  const [loading, setLoading] = useState(true)
  const [stats, setStats] = useState({
    totalUsers: 0,
    activeUsers: 0,
    totalIncome: 0,
    totalExpenses: 0,
    netProfit: 0
  })

  useEffect(() => {
    if (user?.email !== 'sumitachar89@gmail.com') {
      window.location.href = '/dashboard'
      return
    }

    const fetchData = async () => {
      try {
        // Fetch users
        const usersQuery = query(collection(db, 'users'))
        const usersSnapshot = await getDocs(usersQuery)
        const usersData = usersSnapshot.docs.map(doc => ({
          uid: doc.id,
          ...doc.data()
        })) as User[]

        setUsers(usersData)

        // Fetch statistics
        const incomeQuery = query(collection(db, 'incomes'))
        const expenseQuery = query(collection(db, 'expenses'))
        
        const [incomeSnapshot, expenseSnapshot] = await Promise.all([
          getDocs(incomeQuery),
          getDocs(expenseQuery)
        ])

        const totalIncome = incomeSnapshot.docs.reduce((sum, doc) => sum + (doc.data().depositAmount || 0), 0)
        const totalExpenses = expenseSnapshot.docs.reduce((sum, doc) => sum + (doc.data().debitedAmount || 0), 0)

        setStats({
          totalUsers: usersData.length,
          activeUsers: usersData.filter(u => u.lastLogin?.seconds > Date.now() / 1000 - 2592000).length,
          totalIncome,
          totalExpenses,
          netProfit: totalIncome - totalExpenses
        })

      } catch (error) {
        console.error('Error fetching admin data:', error)
      } finally {
        setLoading(false)
      }
    }

    fetchData()
  }, [user])

  const toggleAdminStatus = async (userId: string, currentStatus: boolean) => {
    if (!confirm(`Are you sure you want to ${currentStatus ? 'remove' : 'grant'} admin privileges?`)) return
    
    try {
      await updateDoc(doc(db, 'users', userId), {
        isAdmin: !currentStatus
      })
      setUsers(users.map(u => u.uid === userId ? { ...u, isAdmin: !currentStatus } : u))
    } catch (error) {
      console.error('Error updating admin status:', error)
    }
  }

  const deleteUser = async (userId: string) => {
    if (!confirm('Are you sure you want to delete this user? This cannot be undone.')) return
    
    try {
      await deleteDoc(doc(db, 'users', userId))
      setUsers(users.filter(u => u.uid !== userId))
    } catch (error) {
      console.error('Error deleting user:', error)
    }
  }

  const exportUserReport = () => {
    const doc = new jsPDF()
    
    // Title
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(20)
    doc.text('User Management Report', 15, 15)
    
    // Metadata
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 15, 22)
    doc.text(`Generated by: ${user?.email}`, 15, 27)
    
    // Stats Summary
    autoTable(doc, {
      body: [
        [
          { 
            content: 'System Statistics',
            styles: { 
              fontStyle: 'bold',
              fontSize: 12,
              textColor: [255, 255, 255],
              fillColor: [79, 70, 229] // indigo-600
            } 
          }
        ],
        [
          `Total Users: ${stats.totalUsers}\n` +
          `Active Users: ${stats.activeUsers}\n` +
          `Total Income: ₹${stats.totalIncome.toFixed(2)}\n` +
          `Total Expenses: ₹${stats.totalExpenses.toFixed(2)}\n` +
          `Net Profit: ₹${stats.netProfit.toFixed(2)}`
        ]
      ],
      startY: 35,
      margin: { left: 15, right: 15 },
      styles: {
        cellPadding: 3,
        lineWidth: 0.5
      }
    })
    
    // User Table
    autoTable(doc, {
      head: [['Email', 'Admin', 'Created', 'Last Login']],
      body: users.map(u => [
        u.email,
        u.isAdmin ? 'Yes' : 'No',
        new Date(u.createdAt.seconds * 1000).toLocaleDateString(),
        u.lastLogin ? new Date(u.lastLogin.seconds * 1000).toLocaleDateString() : 'Never'
      ]),
      startY: 80,
      margin: { left: 15, right: 15 },
      styles: {
        cellPadding: 4,
        fontSize: 10,
        lineWidth: 0.3
      },
      headStyles: {
        fillColor: [249, 250, 251], // gray-50
        textColor: [107, 114, 128], // gray-500
        fontStyle: 'bold'
      },
      columnStyles: {
        0: { cellWidth: 'auto' },
        1: { halign: 'center' },
        2: { halign: 'center' },
        3: { halign: 'center' }
      }
    })
    
    doc.save(`user-report-${new Date().toISOString().slice(0, 10)}.pdf`)
  }

  if (loading) {
    return (
      <div className="flex justify-center items-center h-screen">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-indigo-500"></div>
      </div>
    )
  }

  return (
    <div className="p-4 md:p-6 lg:p-8">
      <div className="bg-white rounded-xl shadow-md overflow-hidden p-6">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-800">Admin Dashboard</h1>
          <p className="text-gray-600 mt-2">Manage system users and view statistics</p>
        </div>

        {/* Statistics Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-6 mb-8">
          <div className="bg-indigo-50 p-4 rounded-lg border border-indigo-100">
            <div className="flex items-center gap-3">
              <UsersIcon className="h-6 w-6 text-indigo-600" />
              <h3 className="text-sm font-medium text-indigo-800">Total Users</h3>
            </div>
            <p className="text-2xl font-bold text-indigo-600 mt-2">{stats.totalUsers}</p>
          </div>

          <div className="bg-green-50 p-4 rounded-lg border border-green-100">
            <div className="flex items-center gap-3">
              <ChartBarIcon className="h-6 w-6 text-green-600" />
              <h3 className="text-sm font-medium text-green-800">Active Users</h3>
            </div>
            <p className="text-2xl font-bold text-green-600 mt-2">{stats.activeUsers}</p>
          </div>

          <div className="bg-blue-50 p-4 rounded-lg border border-blue-100">
            <div className="flex items-center gap-3">
              <CreditCardIcon className="h-6 w-6 text-blue-600" />
              <h3 className="text-sm font-medium text-blue-800">Total Income</h3>
            </div>
            <p className="text-2xl font-bold text-blue-600 mt-2">${stats.totalIncome.toFixed(2)}</p>
          </div>

          <div className="bg-red-50 p-4 rounded-lg border border-red-100">
            <div className="flex items-center gap-3">
              <CreditCardIcon className="h-6 w-6 text-red-600" />
              <h3 className="text-sm font-medium text-red-800">Total Expenses</h3>
            </div>
            <p className="text-2xl font-bold text-red-600 mt-2">${stats.totalExpenses.toFixed(2)}</p>
          </div>

          <div className={`p-4 rounded-lg border ${
            stats.netProfit >= 0 
              ? 'bg-green-50 border-green-100' 
              : 'bg-red-50 border-red-100'
          }`}>
            <div className="flex items-center gap-3">
              <ChartBarIcon className={`h-6 w-6 ${
                stats.netProfit >= 0 ? 'text-green-600' : 'text-red-600'
              }`} />
              <h3 className={`text-sm font-medium ${
                stats.netProfit >= 0 ? 'text-green-800' : 'text-red-800'
              }`}>Net Profit</h3>
            </div>
            <p className={`text-2xl font-bold mt-2 ${
              stats.netProfit >= 0 ? 'text-green-600' : 'text-red-600'
            }`}>
              ${stats.netProfit.toFixed(2)}
            </p>
          </div>
        </div>

        {/* User Management */}
        <div className="mb-6">
          <div className="flex justify-between items-center mb-4">
            <h2 className="text-xl font-semibold text-gray-800">User Management</h2>
            <button
              onClick={exportUserReport}
              className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors"
            >
              <ArrowDownTrayIcon className="h-5 w-5" />
              Export Report
            </button>
          </div>

          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Email
                  </th>
                  <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Admin
                  </th>
                  <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Created
                  </th>
                  <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Last Login
                  </th>
                  <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {users.map((user) => (
                  <tr key={user.uid} className="hover:bg-gray-50">
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                      {user.email}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {user.isAdmin ? (
                        <span className="px-2 py-1 bg-green-100 text-green-800 rounded-full text-xs">
                          Admin
                        </span>
                      ) : (
                        <span className="px-2 py-1 bg-gray-100 text-gray-800 rounded-full text-xs">
                          User
                        </span>
                      )}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {new Date(user.createdAt.seconds * 1000).toLocaleDateString()}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {user.lastLogin ? (
                        new Date(user.lastLogin.seconds * 1000).toLocaleDateString()
                      ) : (
                        'Never'
                      )}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium space-x-2">
                      <button
                        onClick={() => toggleAdminStatus(user.uid, user.isAdmin)}
                        className="text-indigo-600 hover:text-indigo-900"
                        title={user.isAdmin ? 'Revoke admin' : 'Make admin'}
                      >
                        <PencilIcon className="h-5 w-5" />
                      </button>
                      {user.email !== 'sumitachar89@gmail.com' && (
                        <button
                          onClick={() => deleteUser(user.uid)}
                          className="text-red-600 hover:text-red-900"
                          title="Delete user"
                        >
                          <TrashIcon className="h-5 w-5" />
                        </button>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* System Controls */}
        <div>
          <h2 className="text-xl font-semibold text-gray-800 mb-4">System Controls</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <button className="flex items-center gap-3 p-4 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors">
              <ArrowPathIcon className="h-6 w-6 text-gray-600" />
              <span>Recalculate Statistics</span>
            </button>
            <button className="flex items-center gap-3 p-4 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors">
              <CogIcon className="h-6 w-6 text-gray-600" />
              <span>System Settings</span>
            </button>
            <button className="flex items-center gap-3 p-4 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors">
              <ChartBarIcon className="h-6 w-6 text-gray-600" />
              <span>Generate Full Report</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}