"use client"
import { useState, useEffect } from 'react'
import { collection, query, getDocs, deleteDoc, doc as firestoreDoc, updateDoc } from 'firebase/firestore'
import { db } from '@/config/firebase'
import { useAuth } from '@/context/AuthContext'
import { TrashIcon, ArrowDownTrayIcon, PencilIcon, MagnifyingGlassIcon } from '@heroicons/react/24/outline'
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import AuthRoute from '../auth/AuthRoute'

interface Expense {
  id: string
  purposeName: string
  debitedAmount: number
  spentName: string
  date: { seconds: number; nanoseconds: number }
  createdBy: string
}

export default function ExpenseList() {
  const { user, isAdmin } = useAuth()
  const [expenses, setExpenses] = useState<Expense[]>([])
  const [filteredExpenses, setFilteredExpenses] = useState<Expense[]>([])
  const [loading, setLoading] = useState(true)
  const [totalExpenses, setTotalExpenses] = useState(0)
  const [searchTerm, setSearchTerm] = useState('')
  const [editingId, setEditingId] = useState<string | null>(null)
  const [editForm, setEditForm] = useState<Partial<Expense>>({})

  // Fetch all expenses
  useEffect(() => {
    const fetchExpenses = async () => {
      try {
        setLoading(true)
        const q = query(collection(db, 'expenses'))
        const querySnapshot = await getDocs(q)
        const expensesData: Expense[] = []
        let total = 0

        querySnapshot.forEach((doc) => {
          const data = doc.data() as Omit<Expense, 'id'>
          expensesData.push({ id: doc.id, ...data })
          total += data.debitedAmount
        })

        setExpenses(expensesData)
        setFilteredExpenses(expensesData)
        setTotalExpenses(total)
      } catch (error) {
        console.error('Error fetching expenses:', error)
      } finally {
        setLoading(false)
      }
    }

    fetchExpenses()
  }, [])

  // Filter expenses based on search term
  useEffect(() => {
    if (searchTerm === '') {
      setFilteredExpenses(expenses)
    } else {
      setFilteredExpenses(
        expenses.filter(expense =>
          expense.purposeName.toLowerCase().includes(searchTerm.toLowerCase()) ||
          expense.spentName.toLowerCase().includes(searchTerm.toLowerCase())
        )
      )
    }
  }, [searchTerm, expenses])

  const handleDelete = async (id: string) => {
    if (!isAdmin || !confirm('Are you sure you want to delete this expense record?')) return
    try {
      await deleteDoc(firestoreDoc(db, 'expenses', id))
      const updatedExpenses = expenses.filter(expense => expense.id !== id)
      setExpenses(updatedExpenses)
      setTotalExpenses(updatedExpenses.reduce((sum, exp) => sum + exp.debitedAmount, 0))
    } catch (error) {
      console.error('Error deleting expense:', error)
    }
  }

  const startEditing = (expense: Expense) => {
    if (!isAdmin) return
    setEditingId(expense.id)
    setEditForm({ ...expense })
  }

  const cancelEditing = () => {
    setEditingId(null)
    setEditForm({})
  }

  const saveEditing = async () => {
    if (!editingId || !isAdmin) return
    try {
      await updateDoc(firestoreDoc(db, 'expenses', editingId), editForm)
      const updatedExpenses = expenses.map(expense => 
        expense.id === editingId ? { ...expense, ...editForm } : expense
      )
      setExpenses(updatedExpenses)
      setTotalExpenses(updatedExpenses.reduce((sum, exp) => sum + exp.debitedAmount, 0))
      setEditingId(null)
    } catch (error) {
      console.error('Error updating expense:', error)
    }
  }

  const downloadPdf = () => {
    const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm' })
    
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(20)
    pdf.setTextColor(31, 41, 55)
    pdf.text('Expense Report', 15, 15)
    
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(10)
    pdf.setTextColor(75, 85, 99)
    pdf.text(`Generated on: ${new Date().toLocaleDateString()}`, 15, 22)
    pdf.text(`Generated by: ${user?.email}`, 15, 27)
    
    autoTable(pdf, {
      body: [
        [
          { 
            content: `Total Expenses: ₹${totalExpenses.toFixed(2)}`,
            styles: { 
              halign: 'right',
              fontStyle: 'bold',
              fontSize: 12,
              textColor: [255, 255, 255],
              fillColor: [239, 68, 68] // red-500
            } 
          }
        ]
      ],
      startY: 35,
      margin: { left: 15, right: 15 }
    })

    autoTable(pdf, {
      head: [
        ['Purpose', 'Amount', 'Spent By', 'Date', 'Added By']
      ],
      body: filteredExpenses.map((expense) => [
        expense.purposeName,
        { content: `-₹${expense.debitedAmount.toFixed(2)}`, styles: { textColor: [239, 68, 68] } },
        expense.spentName,
        new Date(expense.date.seconds * 1000).toLocaleDateString(),
        expense.createdBy
      ]),
      startY: 45,
      margin: { left: 15, right: 15 },
      styles: {
        fontSize: 10,
        textColor: [31, 41, 55],
        lineColor: [209, 213, 219],
        lineWidth: 0.3
      },
      headStyles: {
        fillColor: [79, 70, 229], // indigo-600
        textColor: [255, 255, 255],
        fontStyle: 'bold'
      },
      alternateRowStyles: {
        fillColor: [249, 250, 251] // gray-50
      },
      columnStyles: {
        0: { fontStyle: 'bold' },
        1: { halign: 'right' }
      },
      didDrawPage: (data) => {
        pdf.setFontSize(8)
        pdf.setTextColor(156, 163, 175)
        pdf.text(
          `Page ${data.pageNumber} of ${pdf.getNumberOfPages()}`,
          pdf.internal.pageSize.width - 20,
          pdf.internal.pageSize.height - 10,
          { align: 'right' }
        )
      }
    })
    
    pdf.save(`expense-report-${new Date().toISOString().slice(0, 10)}.pdf`)
  }

  if (loading) {
    return (
      <div className="flex justify-center items-center h-64">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-indigo-500"></div>
      </div>
    )
  }

  return (
    <AuthRoute>
      <div className="p-4 sm:p-6">
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden p-4 sm:p-6">
          <div className="mb-6 flex flex-col sm:flex-row justify-between items-start gap-4">
            <div>
              <h2 className="text-2xl sm:text-3xl font-bold text-gray-800">Expense Records</h2>
              <p className="text-gray-600 mt-1 sm:mt-2 text-sm sm:text-base">
                All expense records are visible to everyone
              </p>
            </div>
            
            <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3 w-full sm:w-auto">
              <div className="relative flex-grow">
                <MagnifyingGlassIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 sm:h-5 sm:w-5 text-gray-400" />
                <input
                  type="text"
                  placeholder="Search by purpose or spender..."
                  className="w-full pl-10 pr-4 py-2 text-sm sm:text-base border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-100 focus:border-indigo-500"
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                />
              </div>
              <button
                onClick={downloadPdf}
                className="flex items-center justify-center gap-2 bg-indigo-600 text-white px-3 sm:px-4 py-2 rounded hover:bg-indigo-700 transition text-sm sm:text-base"
              >
                <ArrowDownTrayIcon className="h-4 w-4 sm:h-5 sm:w-5" />
                <span className="whitespace-nowrap">Export PDF</span>
              </button>
            </div>
          </div>

          <div className="mb-6">
            <div className="bg-red-50 p-4 sm:p-6 rounded-lg border border-red-100">
              <h3 className="text-sm sm:text-base font-medium text-red-800">Total Expenses</h3>
              <p className="text-2xl sm:text-3xl font-bold text-red-600 mt-1">
                ₹{totalExpenses.toFixed(2)}
              </p>
            </div>
          </div>

          <div className="overflow-x-auto">
            <div className="min-w-full inline-block align-middle">
              <div className="overflow-hidden border border-gray-200 rounded-lg">
                <table className="min-w-full divide-y divide-gray-200">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="px-3 py-2 sm:px-4 sm:py-3 text-left text-xs sm:text-sm font-medium text-gray-500 uppercase tracking-wider">Purpose</th>
                      <th className="px-3 py-2 sm:px-4 sm:py-3 text-left text-xs sm:text-sm font-medium text-gray-500 uppercase tracking-wider">Amount</th>
                      <th className="px-3 py-2 sm:px-4 sm:py-3 text-left text-xs sm:text-sm font-medium text-gray-500 uppercase tracking-wider">Spent By</th>
                      <th className="px-3 py-2 sm:px-4 sm:py-3 text-left text-xs sm:text-sm font-medium text-gray-500 uppercase tracking-wider">Date</th>
                      {isAdmin && (
                        <th className="px-3 py-2 sm:px-4 sm:py-3 text-left text-xs sm:text-sm font-medium text-gray-500 uppercase tracking-wider">Actions</th>
                      )}
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    {filteredExpenses.length === 0 ? (
                      <tr>
                        <td colSpan={isAdmin ? 5 : 4} className="px-4 py-4 text-center text-gray-500 text-sm sm:text-base">
                          {searchTerm ? 'No matching records found' : 'No expense records found'}
                        </td>
                      </tr>
                    ) : (
                      filteredExpenses.map((expense) => (
                        <tr key={expense.id} className="hover:bg-gray-50">
                          <td className="px-3 py-3 whitespace-nowrap">
                            <div className="text-sm sm:text-base font-medium text-gray-900">
                              {editingId === expense.id ? (
                                <input
                                  className="w-full border px-2 py-1 rounded text-sm sm:text-base"
                                  value={editForm.purposeName || ''}
                                  onChange={(e) => setEditForm({ ...editForm, purposeName: e.target.value })}
                                />
                              ) : (
                                expense.purposeName
                              )}
                            </div>
                            <div className="text-xs text-gray-500 mt-1">
                              Added by: {expense.createdBy}
                            </div>
                          </td>
                          <td className="px-3 py-3 whitespace-nowrap text-sm sm:text-base font-medium text-red-600">
                            {editingId === expense.id ? (
                              <input
                                type="number"
                                className="w-full border px-2 py-1 rounded text-sm sm:text-base"
                                value={editForm.debitedAmount || ''}
                                onChange={(e) => setEditForm({ ...editForm, debitedAmount: parseFloat(e.target.value) })}
                              />
                            ) : (
                              `-₹${expense.debitedAmount.toFixed(2)}`
                            )}
                          </td>
                          <td className="px-3 py-3 whitespace-nowrap text-sm sm:text-base text-gray-500">
                            {editingId === expense.id ? (
                              <input
                                className="w-full border px-2 py-1 rounded text-sm sm:text-base"
                                value={editForm.spentName || ''}
                                onChange={(e) => setEditForm({ ...editForm, spentName: e.target.value })}
                              />
                            ) : (
                              expense.spentName
                            )}
                          </td>
                          <td className="px-3 py-3 whitespace-nowrap text-sm sm:text-base text-gray-500">
                            {new Date(expense.date.seconds * 1000).toLocaleDateString('en-US', {
                              year: 'numeric',
                              month: 'short',
                              day: 'numeric'
                            })}
                          </td>
                          {isAdmin && (
                            <td className="px-3 py-3 whitespace-nowrap text-sm sm:text-base text-gray-500">
                              {editingId === expense.id ? (
                                <div className="flex gap-2">
                                  <button
                                    onClick={saveEditing}
                                    className="text-green-600 hover:text-green-800 text-sm sm:text-base px-2 py-1 rounded bg-green-50 hover:bg-green-100"
                                  >
                                    Save
                                  </button>
                                  <button
                                    onClick={cancelEditing}
                                    className="text-gray-600 hover:text-gray-800 text-sm sm:text-base px-2 py-1 rounded bg-gray-50 hover:bg-gray-100"
                                  >
                                    Cancel
                                  </button>
                                </div>
                              ) : (
                                <div className="flex gap-2">
                                  <button
                                    onClick={() => startEditing(expense)}
                                    className="text-blue-600 hover:text-blue-800"
                                    title="Edit"
                                  >
                                    <PencilIcon className="h-4 w-4 sm:h-5 sm:w-5" />
                                  </button>
                                  <button
                                    onClick={() => handleDelete(expense.id)}
                                    className="text-red-600 hover:text-red-800"
                                    title="Delete"
                                  >
                                    <TrashIcon className="h-4 w-4 sm:h-5 sm:w-5" />
                                  </button>
                                </div>
                              )}
                            </td>
                          )}
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </AuthRoute>
  )
}