"use client"
import { useState, useEffect } from 'react'
import { collection, query, getDocs, deleteDoc, doc, updateDoc } from 'firebase/firestore'
import { db } from '@/config/firebase'
import { useAuth } from '@/context/AuthContext'
import { TrashIcon, PencilIcon, ArrowDownTrayIcon, XMarkIcon, MagnifyingGlassIcon } from '@heroicons/react/24/outline'
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { AuthRoute } from '../auth/AuthRoute'

interface Income {
  id: string
  name: string
  estimatedAmount: number
  depositAmount: number
  address: string
  collectorName: string
  date: { seconds: number; nanoseconds: number }
  createdBy: string
}

export default function IncomeList() {
  const { user, isAdmin } = useAuth()
  const [incomes, setIncomes] = useState<Income[]>([])
  const [filteredIncomes, setFilteredIncomes] = useState<Income[]>([])
  const [loading, setLoading] = useState(true)
  const [searchTerm, setSearchTerm] = useState('')
  const [editingId, setEditingId] = useState<string | null>(null)
  const [editForm, setEditForm] = useState<Partial<Income>>({})

  // Fetch all incomes (both admin and regular users can see all)
  useEffect(() => {
    const fetchIncomes = async () => {
      try {
        const q = query(collection(db, 'incomes'))
        const querySnapshot = await getDocs(q)
        const incomesData: Income[] = querySnapshot.docs.map(doc => ({
          id: doc.id,
          ...doc.data()
        } as Income))
        
        setIncomes(incomesData)
        setFilteredIncomes(incomesData)
      } catch (error) {
        console.error('Error fetching incomes:', error)
      } finally {
        setLoading(false)
      }
    }

    fetchIncomes()
  }, [])

  // Filter incomes based on search term
  useEffect(() => {
    if (searchTerm === '') {
      setFilteredIncomes(incomes)
    } else {
      setFilteredIncomes(
        incomes.filter(income =>
          income.name.toLowerCase().includes(searchTerm.toLowerCase())
        )
      )
    }
  }, [searchTerm, incomes])

  // Only admin can delete
  const handleDelete = async (id: string) => {
    if (!isAdmin || !confirm('Are you sure you want to delete this record?')) return
    try {
      await deleteDoc(doc(db, 'incomes', id))
      setIncomes(incomes.filter(income => income.id !== id))
    } catch (error) {
      console.error('Error deleting income:', error)
    }
  }

  // Only admin can edit
  const startEditing = (income: Income) => {
    if (!isAdmin) return
    setEditingId(income.id)
    setEditForm({ ...income })
  }

  const cancelEditing = () => {
    setEditingId(null)
    setEditForm({})
  }

  const saveEditing = async () => {
    if (!editingId || !isAdmin) return
    try {
      await updateDoc(doc(db, 'incomes', editingId), editForm)
      setIncomes(incomes.map(income => 
        income.id === editingId ? { ...income, ...editForm } : income
      ))
      setEditingId(null)
    } catch (error) {
      console.error('Error updating income:', error)
    }
  }

  const downloadPdf = () => {
    const doc = new jsPDF({ orientation: 'landscape', unit: 'mm' })
    
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(20)
    doc.text('Income Report', 15, 15)
    
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 15, 22)
    doc.text(`Generated by: ${user?.email}`, 15, 27)
    
    autoTable(doc, {
      head: [['Name', 'Estimated Amount', 'Deposit Amount', 'Collector', 'Date', 'Added By']],
      body: filteredIncomes.map(income => [
        income.name,
        `₹${income.estimatedAmount.toFixed(2)}`,
        `₹${income.depositAmount.toFixed(2)}`,
        income.collectorName,
        new Date(income.date.seconds * 1000).toLocaleDateString(),
        income.createdBy
      ]),
      startY: 35,
      styles: {
        cellPadding: 4,
        fontSize: 10,
        lineWidth: 0.3
      },
      headStyles: {
        fillColor: [79, 70, 229], // indigo-600
        textColor: [255, 255, 255],
        fontStyle: 'bold'
      },
      alternateRowStyles: {
        fillColor: [249, 250, 251] // gray-50
      }
    })
    
    doc.save(`income-report-${new Date().toISOString().slice(0, 10)}.pdf`)
  }

  if (loading) {
    return (
      <div className="flex justify-center items-center h-64">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-indigo-500"></div>
      </div>
    )
  }

  return (
    <AuthRoute>
      <div className="p-4 md:p-6 lg:p-8">
        <div className="bg-white rounded-xl shadow-md overflow-hidden p-6">
          <div className="mb-8 flex flex-col md:flex-row justify-between items-start gap-4">
            <div>
              <h2 className="text-3xl font-bold text-gray-800">Income Records</h2>
              <p className="text-gray-600 mt-2">All income records are visible to everyone</p>
            </div>
            
            <div className="flex items-center gap-4">
              <div className="relative">
                <MagnifyingGlassIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 h-5 w-5 text-gray-400" />
                <input
                  type="text"
                  placeholder="Search by name..."
                  className="pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-100 focus:border-indigo-500"
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                />
              </div>
              <button
                onClick={downloadPdf}
                className="flex items-center gap-2 bg-indigo-600 text-white px-4 py-2 rounded hover:bg-indigo-700 transition"
              >
                <ArrowDownTrayIcon className="h-5 w-5" />
                Export
              </button>
            </div>
          </div>

          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Name</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Estimated</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Deposit</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Collector</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Address</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Date</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Added By</th>
                  {isAdmin && <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Actions</th>}
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {filteredIncomes.length === 0 ? (
                  <tr>
                    <td colSpan={isAdmin ? 8 : 7} className="px-6 py-4 text-center text-gray-500">
                      {searchTerm ? 'No matching records found' : 'No income records found'}
                    </td>
                  </tr>
                ) : (
                  filteredIncomes.map((income) => (
                    <tr key={income.id} className="hover:bg-gray-50">
                      <td className="px-4 py-4">
                        {editingId === income.id ? (
                          <input
                            className="w-full border px-2 py-1 rounded"
                            value={editForm.name || ''}
                            onChange={(e) => setEditForm({ ...editForm, name: e.target.value })}
                          />
                        ) : (
                          income.name
                        )}
                      </td>
                      <td className="px-4 py-4">
                        {editingId === income.id ? (
                          <input
                            type="number"
                            className="w-full border px-2 py-1 rounded"
                            value={editForm.estimatedAmount || ''}
                            onChange={(e) => setEditForm({ ...editForm, estimatedAmount: parseFloat(e.target.value) })}
                          />
                        ) : (
                          `₹${income.estimatedAmount.toFixed(2)}`
                        )}
                      </td>
                      <td className="px-4 py-4">
                        {editingId === income.id ? (
                          <input
                            type="number"
                            className="w-full border px-2 py-1 rounded"
                            value={editForm.depositAmount || ''}
                            onChange={(e) => setEditForm({ ...editForm, depositAmount: parseFloat(e.target.value) })}
                          />
                        ) : (
                          `₹${income.depositAmount.toFixed(2)}`
                        )}
                      </td>
                      <td className="px-4 py-4">
                        {editingId === income.id ? (
                          <input
                            className="w-full border px-2 py-1 rounded"
                            value={editForm.collectorName || ''}
                            onChange={(e) => setEditForm({ ...editForm, collectorName: e.target.value })}
                          />
                        ) : (
                          income.collectorName
                        )}
                      </td>
                      <td className="px-4 py-4">
                        {editingId === income.id ? (
                          <input
                            className="w-full border px-2 py-1 rounded"
                            value={editForm.address || ''}
                            onChange={(e) => setEditForm({ ...editForm, address: e.target.value })}
                          />
                        ) : (
                          income.address
                        )}
                      </td>
                      <td className="px-4 py-4">
                        {new Date(income.date.seconds * 1000).toLocaleDateString('en-US', {
                          year: 'numeric',
                          month: 'short',
                          day: 'numeric'
                        })}
                      </td>
                      <td className="px-4 py-4">
                        {income.createdBy}
                      </td>
                      {isAdmin && (
                        <td className="px-4 py-4 space-x-2">
                          {editingId === income.id ? (
                            <>
                              <button
                                onClick={saveEditing}
                                className="text-green-600 hover:text-green-800"
                              >
                                Save
                              </button>
                              <button
                                onClick={cancelEditing}
                                className="text-gray-500 hover:text-black"
                              >
                                <XMarkIcon className="h-5 w-5" />
                              </button>
                            </>
                          ) : (
                            <>
                              <button
                                onClick={() => startEditing(income)}
                                className="text-blue-600 hover:text-blue-800"
                              >
                                <PencilIcon className="h-5 w-5" />
                              </button>
                              <button
                                onClick={() => handleDelete(income.id)}
                                className="text-red-600 hover:text-red-800"
                              >
                                <TrashIcon className="h-5 w-5" />
                              </button>
                            </>
                          )}
                        </td>
                      )}
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </AuthRoute>
  )
}